[server]
port = 8000

# Refers to the maximum total file size of all documents in /upload/
# Case sensitive! Use values such as B, kb, kB, KiB, MB, MiB, GB, GiB
maxsize = "15MB"

# How long a file should exist on the server in seconds 
filelifetime = 3600

# How often the server should check if a file's lifetime has expired
# and needs to be deleted in seconds
deletionchecktime = 3

# Whether or not everything uploaded should be deleted when the server closes.
# 1 = True. Delete everything on shutdown.
# 0 = False (Fallback). Keep files.
# Note that files are no longer automatically deleted when expiring once the server is down.
deleteonshutdown = 0 
[interface]

# Controls whether "filelifetime" are shown to users.
# 1 = True. Should be shown.
# 0 = False (Fallback). Do not show.
shouldfileconfigbepublic = 1


