[server]

# Controls whether the server is publicly accessible via https and your ipv6 address.
# 1 = True. Server will be public.
# 0 = False (Fallback). Server will be http and LAN only
shouldserverbepublic = 1

# How long until the server should shut down automatically. Set to any value <= 0 to never shut down 
# on its own
serverlifetime = 3600000 # Seconds

# Ports and localhost, make sure these ports aren't blocked by your firewall!
http_port = 8000
https_port = 8443
local_host = "0.0.0.0"

# Refers to the maximum total file size of all documents in /upload/. In other words, the directory will
# not exceed this value, and file uploads will be denied if it would cause this value to be exceeded.
# Case sensitive! Use values such as B, kb, kB, KiB, MB, MiB, GB, GiB
maxsize = "15MB"

# How long a file should exist on the server
maxfilelifetime = 3600 # Seconds

# Time between file deletion jobs
deletionchecktime = 120 # Seconds

# Whether or not everything uploaded should be deleted when the server closes.
# 1 = True. Delete everything on shutdown.
# 0 = False (Fallback). Keep files.
deleteonshutdown = 1
[interface]

# Controls whether "filelifetime" and (remaining) "serverlifetime" are shown to users.
# 1 = True. Should be shown.
# 0 = False (Fallback). Do not show.
shouldfileconfigbepublic = 1


